<?php

/**
 * BaseLienMembreProjet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $role
 * @property integer $projet_id
 * @property integer $membre_id
 * @property Membre $Membre
 * @property Projet $Projet
 * 
 * @method enum             getRole()      Returns the current record's "role" value
 * @method integer          getProjetId()  Returns the current record's "projet_id" value
 * @method integer          getMembreId()  Returns the current record's "membre_id" value
 * @method Membre           getMembre()    Returns the current record's "Membre" value
 * @method Projet           getProjet()    Returns the current record's "Projet" value
 * @method LienMembreProjet setRole()      Sets the current record's "role" value
 * @method LienMembreProjet setProjetId()  Sets the current record's "projet_id" value
 * @method LienMembreProjet setMembreId()  Sets the current record's "membre_id" value
 * @method LienMembreProjet setMembre()    Sets the current record's "Membre" value
 * @method LienMembreProjet setProjet()    Sets the current record's "Projet" value
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseLienMembreProjet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lien_membre_projet');
        $this->hasColumn('role', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Intervenant',
              1 => 'Commercial',
              2 => 'Contact',
              3 => 'Redacteur',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('membre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Membre', array(
             'local' => 'membre_id',
             'foreign' => 'id'));

        $this->hasOne('Projet', array(
             'local' => 'projet_id',
             'foreign' => 'id'));
    }
}