<?php

/**
 * BaseProjetEventType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $abreviation
 * @property string $description
 * @property integer $ordre
 * @property integer $obligatoire
 * 
 * @method string          getAbreviation() Returns the current record's "abreviation" value
 * @method string          getDescription() Returns the current record's "description" value
 * @method integer         getOrdre()       Returns the current record's "ordre" value
 * @method integer         getObligatoire() Returns the current record's "obligatoire" value
 * @method ProjetEventType setAbreviation() Sets the current record's "abreviation" value
 * @method ProjetEventType setDescription() Sets the current record's "description" value
 * @method ProjetEventType setOrdre()       Sets the current record's "ordre" value
 * @method ProjetEventType setObligatoire() Sets the current record's "obligatoire" value
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjetEventType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projet_event_type');
        $this->hasColumn('abreviation', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ordre', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('obligatoire', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}