<?php

/**
 * BaseProjetEventType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $abreviation
 * @property string $description
 * @property Doctrine_Collection $ProjetEvent
 * 
 * @method string              getAbreviation() Returns the current record's "abreviation" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getProjetEvent() Returns the current record's "ProjetEvent" collection
 * @method ProjetEventType     setAbreviation() Sets the current record's "abreviation" value
 * @method ProjetEventType     setDescription() Sets the current record's "description" value
 * @method ProjetEventType     setProjetEvent() Sets the current record's "ProjetEvent" collection
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProjetEventType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projet_event_type');
        $this->hasColumn('abreviation', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProjetEvent', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}