<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date
 * @property string $commentaire
 * @property integer $prospect_id
 * @property integer $membre_id
 * @property integer $type_contact_id
 * @property Prospect $Prospect
 * @property Membre $Membre
 * @property TypeContact $TypeContact
 * 
 * @method date        getDate()            Returns the current record's "date" value
 * @method string      getCommentaire()     Returns the current record's "commentaire" value
 * @method integer     getProspectId()      Returns the current record's "prospect_id" value
 * @method integer     getMembreId()        Returns the current record's "membre_id" value
 * @method integer     getTypeContactId()   Returns the current record's "type_contact_id" value
 * @method Prospect    getProspect()        Returns the current record's "Prospect" value
 * @method Membre      getMembre()          Returns the current record's "Membre" value
 * @method TypeContact getTypeContact()     Returns the current record's "TypeContact" value
 * @method Contact     setDate()            Sets the current record's "date" value
 * @method Contact     setCommentaire()     Sets the current record's "commentaire" value
 * @method Contact     setProspectId()      Sets the current record's "prospect_id" value
 * @method Contact     setMembreId()        Sets the current record's "membre_id" value
 * @method Contact     setTypeContactId()   Sets the current record's "type_contact_id" value
 * @method Contact     setProspect()        Sets the current record's "Prospect" value
 * @method Contact     setMembre()          Sets the current record's "Membre" value
 * @method Contact     setTypeContact()     Sets the current record's "TypeContact" value
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('commentaire', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('prospect_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('membre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_contact_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Prospect', array(
             'local' => 'prospect_id',
             'foreign' => 'id'));

        $this->hasOne('Membre', array(
             'local' => 'membre_id',
             'foreign' => 'id'));

        $this->hasOne('TypeContact', array(
             'local' => 'type_contact_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}