<?php

/**
 * BaseLienMembreProjet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $projet_id
 * @property integer $membre_id
 * 
 * @method integer          getProjetId()  Returns the current record's "projet_id" value
 * @method integer          getMembreId()  Returns the current record's "membre_id" value
 * @method LienMembreProjet setProjetId()  Sets the current record's "projet_id" value
 * @method LienMembreProjet setMembreId()  Sets the current record's "membre_id" value
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseLienMembreProjet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lien_membre_projet');
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('membre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}