<?php

/**
 * LienMembreProjetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LienMembreProjetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LienMembreProjetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LienMembreProjet');
    }
}