<?php

/**
 * MembreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MembreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MembreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Membre');
    }
}