<?php

/**
 * Projet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Projet extends BaseProjet
{
  
  public function getRespo()
  {
    return $this->getMembre();
  }
}
