<?php

/**
 * Projet
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Projet extends BaseProjet
{
  public function __toString()
  {
    return $this->getNumero().' / '.$this->getNom();
  }

  public function getRespo()
  {
    foreach($this->getLienMembreProjet() as $lien)
      if(($lien->getRole()) == 'Chef de projet')
        return $lien->getMembre();

    return null;
  }

  public function getEtat()
  {
    return '';
  }

  public function getQualite()
  {
    return '';
  }

  public function getParticipations()
  {
    return Doctrine_Core::getTable('LienMembreProjet')
      ->createQuery('l')
      ->select('m.id, m.nom, m.prenom, m.username, l.role, l.JEH')
      ->leftJoin('l.Membre m')
      ->where('l.projet_id = ?', array($this->getId()))
      ->orderBy('l.role')
      ->execute();
  }
}
