<?php

/**
 * ProjetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Projet');
    }
}