<?php

/**
 * ProjetEventType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class ProjetEventType extends BaseProjetEventType
{
  public function __toString() {
    return $this->getAbreviation().' / '.$this->getDescription();
  }
}
