<?php

/**
 * ProjetEventTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjetEventTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjetEventTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjetEventType');
    }
}