<?php

/**
 * ProjetEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class ProjetEvent extends BaseProjetEvent
{
  public function save(Doctrine_Connection $conn = null)
  {
    if($this->getProjetEventType()->getDescription() == 'Commentaire')
    {
      $this->setDate(NULL);
    }

    return parent::save($conn);
  }
  
}
