<?php

/**
 * Projet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Projet extends BaseProjet
{
  public function __toString()
  {
    return $this->getNumero().' / '.$this->getNom();
  }

  public function getRespo()
  {
    return $this->getMembre();
  }

  public function getEtat()
  {
    return '';
  }

  public function getQualite()
  {
    return '';
  }
  
  public static function getAllParticipants($projetId)
  {
    return Doctrine_Core::getTable('LienMembreProjet')
      ->createQuery('l')
      ->select('m.id, m.nom, m.prenom, m.username, l.role')
      ->leftJoin('l.Membre m')
      ->where('l.projet_id = ?', array($projetId))
      ->execute();
  }
}
