<?php

/**
 * Prospect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    appel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Prospect extends BaseProspect
{
    public function __toString() {
        return $this->getNom();
    }
    
    public function getLinkForSiteWeb()
    {
       return Tools::addHtmlLinks($this->getSiteWeb());
    }
}
