<?php

/**
 * QuittanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuittanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuittanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quittance');
    }
}