<?php

/**
 * Quittance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Quittance extends BaseQuittance
{
  public function __toString()
  {
    return $this->getAnnee()."/".($this->getAnnee() + 1);
  }
}
