<?php

/**
 * TypeContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TypeContact extends BaseTypeContact
{
  public function __toString() {
      return $this->getNom();
  }
}
