# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: membre, action: index }

### Annuaire
annuaire:
  url: /annuaire/:action/*
  param: { module: membre }

annuaire.index:
  url:  /annuaire/
  param: { module: membre, action: index }

## Carte
carte:
  url: /carte/:action/*
  param: { module: carte }

annuaire.index:
  url:  /carte/
  param: { module: carte, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
