# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        ERP IARISS
    description:  ERP simple pour la gestion de la Pépinière Junior-Entreprise IARISS
    #keywords:     symfony, project
    language:     fr
    #robots:       index, follow

  stylesheets:    [main, tablesorter]

  javascripts:    [jquery-1.7.min.js, jquery.tablesorter.min.js, scripts.js]

  has_layout:     true
  layout:         layout
