indicateursSuccess:
  javascripts:
    - jquery-1.4.2.min.js
    - jquery.flot.min.js
    - jquery.flot.selection.min.js
    - excanvas.min.js: { condition: IE }

all:
  stylesheets: [style, page-annuaire]
